name: Automatic Update Workflow

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 6 minutes
  workflow_dispatch:  # Allows manual triggering as well

jobs:
  fetch-and-update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to the latest version

      - name: Fetch content from URL
        run: |
          CONTENT_URL='https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/list.txt'
          curl -o hosts $CONTENT_URL
          cat hosts  # Print the fetched content for debugging

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add hosts
          git commit -m "Update hosts file with content from $CONTENT_URL" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
